import { describe, expect, it } from "vitest";
import {
  dashboardProfitabilityApiResponseSchema,
  productAnalyticsSnapshotApiResponseSchema,
} from "./protected-app";

describe("@marginflow/validation protected app schemas", () => {
  it("accepts full dashboard profitability payloads with explicit analytic fields", () => {
    const result = dashboardProfitabilityApiResponseSchema.safeParse({
      data: {
        channels: [
          {
            channel: "mercadolivre",
            summary: {
              avgRoi: "260.00",
              avgRoas: "20.00",
              avgTicket: "200.00",
              breakEvenRevenue: "80.00",
              breakEvenUnits: "1.00",
              contributionMargin: "120.00",
              grossMarginPercent: "65.00",
              grossProfit: "130.00",
              grossRevenue: "200.00",
              netProfit: "120.00",
              netRevenue: "200.00",
              ordersCount: 1,
              totalAdCosts: "10.00",
              totalCogs: "50.00",
              totalFees: "20.00",
              totalManualExpenses: "0.00",
              totalReturns: 0,
              unitsSold: 2,
            },
          },
        ],
        products: [
          {
            adSpend: "10.00",
            channel: "mercadolivre",
            grossProfit: "130.00",
            margin: "65.00",
            marketplaceCommission: "20.00",
            netSales: 2,
            packagingCost: "0.00",
            productCost: "50.00",
            productId: "prod_1",
            productName: "Premium Notebook",
            returns: 0,
            revenue: "200.00",
            roi: "260.00",
            roas: "20.00",
            salePrice: "100.00",
            sales: 2,
            shippingCost: "0.00",
            sku: "NB-1",
            summary: {
              avgRoi: "260.00",
              avgRoas: "20.00",
              avgTicket: "200.00",
              breakEvenRevenue: "80.00",
              breakEvenUnits: "1.00",
              contributionMargin: "120.00",
              grossMarginPercent: "65.00",
              grossProfit: "130.00",
              grossRevenue: "200.00",
              netProfit: "120.00",
              netRevenue: "200.00",
              ordersCount: 1,
              totalAdCosts: "10.00",
              totalCogs: "50.00",
              totalFees: "20.00",
              totalManualExpenses: "0.00",
              totalReturns: 0,
              unitsSold: 2,
            },
            taxAmount: "0.00",
          },
        ],
      },
      error: null,
    });

    expect(result.success).toBe(true);
  });

  it("rejects product analytics rows when required fields are missing", () => {
    const result = productAnalyticsSnapshotApiResponseSchema.safeParse({
      data: {
        adCosts: [],
        catalogStats: {
          activeProducts: 1,
          archivedProducts: 0,
          pendingSyncProducts: 0,
          productsWithCost: 1,
          productsWithoutCost: 0,
          syncedProductsTotal: 0,
          totalAdCosts: 0,
          totalManualExpenses: 0,
          totalProductCosts: 1,
          totalProducts: 1,
        },
        dataGaps: [],
        financialState: "ready",
        manualExpenses: [],
        mercadoLivreSyncStatus: {
          activeRun: null,
          availability: {
            canRun: true,
            currentWindowKey: "2026-05-13-morning",
            currentWindowLabel: "Manha",
            currentWindowSlot: "morning",
            lastSuccessfulSyncAt: null,
            message: "Sync is available for the current daily window.",
            nextAvailableAt: "2026-05-13T09:00:00.000Z",
            provider: "mercadolivre",
            reason: "available",
          },
          lastCompletedRun: null,
        },
        monthlyPerformanceRows: [
          {
            advertisingCost: "0.00",
            channel: "mercadolivre",
            commissionRate: "0.100000",
            packagingCost: "0.00",
            productName: "Produto um",
            referenceMonth: "2026-05-01",
            returnsQuantity: 0,
            salePrice: "20.00",
            salesQuantity: 1,
            shippingFee: "0.00",
            sku: "SKU-1",
            taxRate: "0.000000",
            unitCost: "10.00",
          },
        ],
        productCosts: [],
        productRows: [
          {
            actualRoas: "0.00",
            adSpend: "0.00",
            channel: "mercadolivre",
            contributionMargin: "10.00",
            dataSource: "sync",
            grossProfit: "10.00",
            hasCost: true,
            hasLinkedMarketplaceSignal: true,
            hasSalesSignal: true,
            insufficientReasons: [],
            isActive: true,
            margin: "10.00",
            marketplaceCommission: "0.00",
            minimumRoas: "Infinity",
            name: "Produto sem custo total",
            netSales: 1,
            packagingCost: "0.00",
            productId: "prod_1",
            revenue: "20.00",
            returns: 0,
            roi: "0.00",
            salePrice: "20.00",
            sales: 1,
            shippingCost: "0.00",
            sku: "SKU-1",
            taxAmount: "0.00",
            totalProfit: "10.00",
            unitProfit: "10.00",
          },
        ],
        products: [],
        scope: {
          companyId: null,
          companyRequired: false,
          referenceMonth: "2026-05-01",
        },
        syncedProducts: [],
      },
      error: null,
    });

    expect(result.success).toBe(false);
  });

  it("accepts analytics snapshots with explicit Infinity fail-safe values", () => {
    const result = productAnalyticsSnapshotApiResponseSchema.safeParse({
      data: {
        adCosts: [],
        catalogStats: {
          activeProducts: 1,
          archivedProducts: 0,
          pendingSyncProducts: 1,
          productsWithCost: 0,
          productsWithoutCost: 1,
          syncedProductsTotal: 1,
          totalAdCosts: 0,
          totalManualExpenses: 0,
          totalProductCosts: 0,
          totalProducts: 1,
        },
        dataGaps: [],
        financialState: "insufficient",
        manualExpenses: [],
        mercadoLivreSyncStatus: {
          activeRun: null,
          availability: {
            canRun: false,
            currentWindowKey: "2026-05-13-afternoon",
            currentWindowLabel: "Tarde",
            currentWindowSlot: "afternoon",
            lastSuccessfulSyncAt: "2026-05-12T19:00:00.000Z",
            message: "This daily sync window was already used. Wait for the next window to open.",
            nextAvailableAt: "2026-05-13T18:00:00.000Z",
            provider: "mercadolivre",
            reason: "window_already_used",
          },
          lastCompletedRun: {
            counts: {
              fees: 1,
              items: 1,
              orders: 1,
              products: 1,
            },
            createdAt: "2026-05-12T19:00:00.000Z",
            cursor: {
              orderedAfter: "2026-05-12T18:59:00.000Z",
            },
            errorSummary: null,
            finishedAt: "2026-05-12T19:03:00.000Z",
            id: "sync_1",
            provider: "mercadolivre",
            startedAt: "2026-05-12T19:00:10.000Z",
            status: "completed",
            updatedAt: "2026-05-12T19:03:00.000Z",
            windowKey: "2026-05-12-evening",
          },
        },
        monthlyPerformanceRows: [
          {
            advertisingCost: "0.00",
            channel: "unknown",
            commissionRate: "0.000000",
            packagingCost: "0.00",
            productName: "Produto Dois",
            referenceMonth: "2026-05-01",
            returnsQuantity: 0,
            salePrice: "80.00",
            salesQuantity: 0,
            shippingFee: "0.00",
            sku: "XYZ-1",
            taxRate: "0.000000",
            unitCost: "0.00",
          },
        ],
        productCosts: [],
        productRows: [
          {
            actualRoas: "0.00",
            adSpend: "0.00",
            channel: "unknown",
            contributionMargin: "0.00",
            dataSource: "sync",
            grossProfit: "0.00",
            hasCost: false,
            hasLinkedMarketplaceSignal: false,
            hasSalesSignal: false,
            insufficientReasons: ["missing_cost", "missing_sales_signal"],
            isActive: true,
            margin: "0.00",
            marketplaceCommission: "0.00",
            minimumRoas: "Infinity",
            name: "Produto Dois",
            netSales: 0,
            packagingCost: "0.00",
            productCost: "0.00",
            productId: "product_2",
            revenue: "0.00",
            returns: 0,
            roi: "0.00",
            salePrice: "80.00",
            sales: 0,
            shippingCost: "0.00",
            sku: "XYZ-1",
            taxAmount: "0.00",
            totalProfit: "0.00",
            unitProfit: "0.00",
          },
        ],
        products: [
          {
            createdAt: "2026-05-01T10:00:00.000Z",
            id: "product_2",
            isActive: true,
            latestCost: null,
            name: "Produto Dois",
            organizationId: "org_123",
            sellingPrice: "80.00",
            sku: "XYZ-1",
            updatedAt: "2026-05-01T10:00:00.000Z",
          },
        ],
        scope: {
          companyId: null,
          companyRequired: false,
          referenceMonth: "2026-05-01",
        },
        syncedProducts: [
          {
            externalProductId: "MLB-1",
            fixedFee: "0.00",
            grossRevenue: "0.00",
            id: "external_1",
            lastOrderedAt: null,
            latestUnitPrice: null,
            linkedProduct: null,
            marketplaceCommission: "0.00",
            netMarketplaceTake: "0.00",
            orderCount: 0,
            provider: "mercadolivre",
            reviewStatus: "unreviewed",
            sku: "XYZ-1",
            shippingCost: "0.00",
            suggestedMatches: [],
            title: "Produto Dois",
            unitsSold: 0,
          },
        ],
      },
      error: null,
    });

    expect(result.success).toBe(true);
  });
});
