import { describe, expect, it } from "vitest";
import type { ProductAnalyticsSnapshot } from "@marginflow/types";
import {
  buildCatalogStats,
  buildProductInsights,
  buildProductTableRows,
  determineFinancialState,
} from "./calculations/product-insights";

const snapshot: ProductAnalyticsSnapshot = {
  adCosts: [],
  catalogStats: {
    activeProducts: 2,
    archivedProducts: 0,
    pendingSyncProducts: 1,
    productsWithCost: 1,
    productsWithoutCost: 1,
    syncedProductsTotal: 1,
    totalAdCosts: 0,
    totalManualExpenses: 0,
    totalProducts: 2,
    totalProductCosts: 1,
  },
  dataGaps: [],
  financialState: "ready",
  manualExpenses: [],
  mercadoLivreSyncStatus: {
    activeRun: null,
    availability: {
      canRun: true,
      currentWindowKey: "2026-05-13-morning",
      currentWindowLabel: "Manha",
      currentWindowSlot: "morning",
      lastSuccessfulSyncAt: null,
      message: "Sync is available for the current daily window.",
      nextAvailableAt: "2026-05-13T09:00:00.000Z",
      provider: "mercadolivre",
      reason: "available",
    },
    lastCompletedRun: null,
  },
  monthlyPerformanceRows: [
    {
      advertisingCost: "10.00",
      channel: "mercadolivre",
      commissionRate: "0.100000",
      packagingCost: "4.00",
      productName: "Product One",
      referenceMonth: "2026-05-01",
      returnsQuantity: 1,
      salePrice: "100.00",
      salesQuantity: 2,
      shippingFee: "12.00",
      sku: "ABC-1",
      taxRate: "0.090000",
      unitCost: "25.00",
    },
    {
      advertisingCost: "0.00",
      channel: "unknown",
      commissionRate: "0.000000",
      packagingCost: "0.00",
      productName: "Product Two",
      referenceMonth: "2026-05-01",
      returnsQuantity: 0,
      salePrice: "80.00",
      salesQuantity: 0,
      shippingFee: "0.00",
      sku: "XYZ-1",
      taxRate: "0.000000",
      unitCost: "0.00",
    },
  ],
  productCosts: [],
  productRows: [
    {
      actualRoas: "20.00",
      adSpend: "10.00",
      channel: "mercadolivre",
      contributionMargin: "120.00",
      dataSource: "monthly_performance",
      grossProfit: "130.00",
      hasCost: true,
      hasLinkedMarketplaceSignal: true,
      hasSalesSignal: true,
      insufficientReasons: [],
      isActive: true,
      margin: "65.00",
      marketplaceCommission: "20.00",
      minimumRoas: "1.67",
      name: "Product One",
      netSales: 2,
      packagingCost: "4.00",
      productCost: "50.00",
      productId: "product_1",
      revenue: "200.00",
      returns: 1,
      roi: "260.00",
      salePrice: "100.00",
      sales: 2,
      shippingCost: "12.00",
      sku: "ABC-1",
      taxAmount: "18.00",
      totalProfit: "120.00",
      unitProfit: "60.00",
    },
    {
      actualRoas: "0.00",
      adSpend: "0.00",
      channel: "unknown",
      contributionMargin: "0.00",
      dataSource: "sync",
      grossProfit: "0.00",
      hasCost: false,
      hasLinkedMarketplaceSignal: false,
      hasSalesSignal: false,
      insufficientReasons: ["missing_cost", "missing_sales_signal"],
      isActive: true,
      margin: "0.00",
      marketplaceCommission: "0.00",
      minimumRoas: "Infinity",
      name: "Product Two",
      netSales: 0,
      packagingCost: "0.00",
      productCost: "0.00",
      productId: "product_2",
      revenue: "0.00",
      returns: 0,
      roi: "0.00",
      salePrice: "80.00",
      sales: 0,
      shippingCost: "0.00",
      sku: "XYZ-1",
      taxAmount: "0.00",
      totalProfit: "0.00",
      unitProfit: "0.00",
    },
  ],
  scope: {
    companyId: "company_1",
    companyRequired: false,
    referenceMonth: "2026-05-01",
  },
  products: [
    {
      createdAt: "2026-05-01T10:00:00.000Z",
      id: "product_1",
      isActive: true,
      latestCost: {
        amount: "25.00",
        costType: "base",
        createdAt: "2026-05-01T10:00:00.000Z",
        currency: "BRL",
        effectiveFrom: "2026-05-01",
        id: "cost_1",
        notes: null,
        organizationId: "org_123",
        productId: "product_1",
        updatedAt: "2026-05-01T10:00:00.000Z",
      },
      name: "Product One",
      organizationId: "org_123",
      sellingPrice: "100.00",
      sku: "ABC-1",
      updatedAt: "2026-05-01T10:00:00.000Z",
    },
    {
      createdAt: "2026-05-01T10:00:00.000Z",
      id: "product_2",
      isActive: true,
      latestCost: null,
      name: "Product Two",
      organizationId: "org_123",
      sellingPrice: "80.00",
      sku: "XYZ-1",
      updatedAt: "2026-05-01T10:00:00.000Z",
    },
  ],
  syncedProducts: [
    {
      externalProductId: "MLB-1",
      fixedFee: "5.00",
      grossRevenue: "200.00",
      id: "external_1",
      lastOrderedAt: "2026-05-01T11:00:00.000Z",
      latestUnitPrice: "100.00",
      linkedProduct: null,
      marketplaceCommission: "20.00",
      netMarketplaceTake: "37.00",
      orderCount: 1,
      provider: "mercadolivre",
      reviewStatus: "unreviewed",
      sku: "XYZ-1",
      shippingCost: "12.00",
      suggestedMatches: [
        {
          isActive: true,
          name: "Product Two",
          productId: "product_2",
          reason: "sku_exact",
          sku: "XYZ-1",
        },
      ],
      title: "Product Two",
      unitsSold: 2,
    },
  ],
};

describe("products foundation helpers", () => {
  it("uses backend catalog stats and financial state as the source of truth", () => {
    expect(buildCatalogStats(snapshot)).toEqual(snapshot.catalogStats);
    expect(determineFinancialState(snapshot)).toBe("ready");
  });

  it("maps analytics rows without local sales simulation or heuristic costs", () => {
    expect(buildProductTableRows(snapshot)).toEqual([
      expect.objectContaining({
        actualRoas: 10,
        adSpend: 10,
        channelLabel: "mercadolivre",
        commissionPct: 10,
        contributionMarginRatio: 0.4,
        minimumRoas: 2.5,
        name: "Product One",
        netLiquidSales: 1,
        packagingCost: 4,
        revenue: 100,
        returns: 1,
        roiRatio: 1.6,
        shipping: 12,
        taxPct: 9,
        totalProfit: 40,
        unitCost: 25,
        unitProfit: 40,
      }),
      expect.objectContaining({
        actualRoas: null,
        adSpend: 0,
        channelLabel: "unknown",
        commissionPct: 0,
        contributionMarginRatio: null,
        minimumRoas: null,
        name: "Product Two",
        netLiquidSales: 0,
        revenue: 0,
        roiRatio: null,
        taxPct: 0,
        totalProfit: 0,
        unitCost: 0,
        unitProfit: null,
      }),
    ]);
  });

  it("derives product insights from the official analytics snapshot", () => {
    const insights = buildProductInsights(
      snapshot,
      snapshot.catalogStats,
      buildProductTableRows(snapshot),
    );

    expect(insights).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          href: "/app/products",
          id: "best-profit-product",
        }),
        expect.objectContaining({
          href: "/app/products",
          id: "highest-returns-product",
        }),
        expect.objectContaining({
          href: "/app/products",
          id: "highest-shipping-product",
        }),
      ]),
    );
  });
});
